In [1]:
from phreeqpy.phreeqcrm.rm_model import PhreeqcRMModel

In [2]:
model = PhreeqcRMModel('all_methods.yaml')

 220  area     = sp_area * M0 * (M / M0)^0.67.
Value set to zero.
 220  area     = sp_area * M0 * (M / M0)^0.67.
Value set to zero.
 220  area     = sp_area * M0 * (M / M0)^0.67.
Value set to zero.
 220  area     = sp_area * M0 * (M / M0)^0.67.
Value set to zero.
 220  area     = sp_area * M0 * (M / M0)^0.67.
Value set to zero.
 220  area     = sp_area * M0 * (M / M0)^0.67.
Value set to zero.
 200  rate_H   = 10^-pk_H * ACT("H+")^nH / ((1 + aAl / CAl)^yAl * (1 + BC / CBC)^xBC).
Value set to zero.
 200  rate_H   = 10^-pk_H * ACT("H+")^nH / ((1 + aAl / CAl)^yAl * (1 + BC / CBC)^xBC).
Value set to zero.
 280  rate_H2O = 10^-pk_H2O / ((1 + aAl / CAl)^yAl * (1 + BC / CBC)^xBC * (1 + aSi / CSi)^zSi).
Value set to zero.
 280  rate_H2O = 10^-pk_H2O / ((1 + aAl / CAl)^yAl * (1 + BC / CBC)^xBC * (1 + aSi / CSi)^zSi).
Value set to zero.
 280  rate_H2O = 10^-pk_H2O / ((1 + aAl / CAl)^yAl * (1 + BC / CBC)^xBC * (1 + aSi / CSi)^zSi).
Value set to zero.
 390  rate_Org = 10^-pk_Org * (R / (1 + R / COr

In [20]:
equi = {name: model.rm_variables[name] for name in model.rm_variables.names if name.startswith('equilibrium_phases_')}

In [23]:
equi['equilibrium_phases_moles_Dolomite'].value

array([0.09310451, 0.09310451, 0.09310451, 0.09310451, 0.09310451,
       0.09310451, 0.09310451, 0.09310451, 0.09310451, 0.09310451,
       0.09310451, 0.09310451, 0.09310451, 0.09310451, 0.09310451,
       0.09310451, 0.09310451, 0.09310451, 0.09310451, 0.09310451,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [30]:
equi

{'equilibrium_phases_moles_Dolomite': RMVariable((BMIPhreeqcRM(), 'equilibrium_phases_moles_Dolomite')),
 'equilibrium_phases_delta_moles_Calcite': RMVariable((BMIPhreeqcRM(), 'equilibrium_phases_delta_moles_Calcite')),
 'equilibrium_phases_moles_Goethite': RMVariable((BMIPhreeqcRM(), 'equilibrium_phases_moles_Goethite')),
 'equilibrium_phases_delta_moles_Goethite': RMVariable((BMIPhreeqcRM(), 'equilibrium_phases_delta_moles_Goethite')),
 'equilibrium_phases_moles_Calcite': RMVariable((BMIPhreeqcRM(), 'equilibrium_phases_moles_Calcite')),
 'equilibrium_phases_delta_moles_Dolomite': RMVariable((BMIPhreeqcRM(), 'equilibrium_phases_delta_moles_Dolomite'))}

In [25]:
gas = {name: model.rm_variables[name] for name in model.rm_variables.names if name.startswith('gas_phase_')}

In [26]:
gas

{'gas_phase_moles_Ntg(g)': RMVariable((BMIPhreeqcRM(), 'gas_phase_moles_Ntg(g)')),
 'gas_phase_phi_CO2(g)': RMVariable((BMIPhreeqcRM(), 'gas_phase_phi_CO2(g)')),
 'gas_phase_pressure_Ntg(g)': RMVariable((BMIPhreeqcRM(), 'gas_phase_pressure_Ntg(g)')),
 'gas_phase_volume': RMVariable((BMIPhreeqcRM(), 'gas_phase_volume')),
 'gas_phase_moles_CO2(g)': RMVariable((BMIPhreeqcRM(), 'gas_phase_moles_CO2(g)')),
 'gas_phase_pressure_CO2(g)': RMVariable((BMIPhreeqcRM(), 'gas_phase_pressure_CO2(g)')),
 'gas_phase_phi_Ntg(g)': RMVariable((BMIPhreeqcRM(), 'gas_phase_phi_Ntg(g)'))}

In [29]:
gas['gas_phase_moles_Ntg(g)'].value

array([0.00282336, 0.00282336, 0.00282336, 0.00282336, 0.00282336,
       0.00282336, 0.00282336, 0.00282336, 0.00282336, 0.00282336,
       0.00282336, 0.00282336, 0.00282336, 0.00282336, 0.00282336,
       0.00282336, 0.00282336, 0.00282336, 0.00282336, 0.00282336,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [27]:
model.molalities

,C,H,K,Ba,N,Na,Si,Mg,Fe,Ntg,Al,Ca,O,Cl,S
0,0.002174,111.014512,0.000018,3.747473e-08,0.0012,0.341984,0.0,0.010552,3.491792e-14,0.000423,0.0,0.010912,56.280182,0.0,0.190847
1,0.002174,111.014512,0.000018,3.747473e-08,0.0012,0.341984,0.0,0.010552,3.491792e-14,0.000423,0.0,0.010912,56.280182,0.0,0.190847
2,0.002174,111.014512,0.000018,3.747473e-08,0.0012,0.341984,0.0,0.010552,3.491792e-14,0.000423,0.0,0.010912,56.280182,0.0,0.190847
3,0.002174,111.014512,0.000018,3.747473e-08,0.0012,0.341984,0.0,0.010552,3.491792e-14,0.000423,0.0,0.010912,56.280182,0.0,0.190847
4,0.002174,111.014512,0.000018,3.747473e-08,0.0012,0.341984,0.0,0.010552,3.491792e-14,0.000423,0.0,0.010912,56.280182,0.0,0.190847
5,0.002174,111.014512,0.000018,3.747473e-08,0.0012,0.341984,0.0,0.010552,3.491792e-14,0.000423,0.0,0.010912,56.280182,0.0,0.190847
6,0.002174,111.014512,0.000018,3.747473e-08,0.0012,0.341984,0.0,0.010552,3.491792e-14,0.000423,0.0,0.010912,56.280182,0.0,0.190847
7,0.002174,111.014512,0.000018,3.747473e-08,0.0012,0.341984,0.0,0.010552,3.491792e-14,0.000423,0.0,0.010912,56.280182,0.0,0.190847
8,0.002174,111.014512,0.000018,3.747473e-08,0.0012,0.341984,0.0,0.010552,3.491792e-14,0.000423,0.0,0.010912,56.280182,0.0,0.190847
9,0.002174,111.014512,0.000018,3.747473e-08,0.0012,0.341984,0.0,0.010552,3.491792e-14,0.000423,0.0,0.010912,56.280182,0.0,0.190847


In [13]:
model.number_of_cells

np.int32(40)

In [14]:
model.yaml_file_name

'all_methods.yaml'

In [16]:
model.get_initial_concentrations(1)

{'H': 110.34975928582965,
 'O': 55.94317716273131,
 'Charge': -7.514582235449926e-05,
 'Al': 0.0,
 'Ba': 3.725033257007232e-08,
 'C': 0.0021606971299047467,
 'Ca': 0.010846273475910929,
 'Cl': 0.0,
 'Fe': 3.470882994054025e-14,
 'K': 1.7481145726446082e-05,
 'Mg': 0.010488646573877167,
 'N': 0.0011927100988685586,
 'Na': 0.3399365104205056,
 'Ntg': 0.00042004030867755443,
 'S': 0.18970431237459978,
 'Si': 0.0}

In [31]:
model.rm_variables.names

{'ComponentCount',
 'Components',
 'Concentrations',
 'CurrentSelectedOutputUserNumber',
 'DensityCalculated',
 'DensityUser',
 'ErrorString',
 'FilePrefix',
 'Gfw',
 'GridCellCount',
 'NthSelectedOutput',
 'Porosity',
 'Pressure',
 'SaturationCalculated',
 'SaturationUser',
 'SelectedOutput',
 'SelectedOutputColumnCount',
 'SelectedOutputCount',
 'SelectedOutputHeadings',
 'SelectedOutputOn',
 'SelectedOutputRowCount',
 'SolutionVolume',
 'Temperature',
 'Time',
 'TimeStep',
 'Viscosity',
 'calculate_value_hermanska_rate',
 'calculate_value_palandri_rate',
 'calculate_value_sar',
 'calculate_value_sverdrup_rate',
 'equilibrium_phases_delta_moles_Calcite',
 'equilibrium_phases_delta_moles_Dolomite',
 'equilibrium_phases_delta_moles_Goethite',
 'equilibrium_phases_moles_Calcite',
 'equilibrium_phases_moles_Dolomite',
 'equilibrium_phases_moles_Goethite',
 'exchange_X_species_log_molality_AlOHX2',
 'exchange_X_species_log_molality_AlX3',
 'exchange_X_species_log_molality_BaX2',
 'exchang

In [34]:
model.rm_variables['exchange_X_species_log_molality_AlOHX2'].value

array([-99.99, -99.99, -99.99, -99.99, -99.99, -99.99, -99.99, -99.99,
       -99.99, -99.99, -99.99, -99.99, -99.99, -99.99, -99.99, -99.99,
       -99.99, -99.99, -99.99, -99.99,   0.  ,   0.  ,   0.  ,   0.  ,
         0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,
         0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ])

In [35]:
model._rm.set_value?

Signature: model._rm.set_value(var_name, value)
Docstring:
@todo
        
File:      ~/Dev/phreeqpy_project/phreeqpy/.pixi/envs/default/lib/python3.14/site-packages/phreeqcrm/phreeqcrm.py
Type:      method

In [36]:
model._rm.set_value_at_indices?

Signature: model._rm.set_value_at_indices(var_name, inds, src)
Docstring:
Set model values at particular indices.

Parameters
----------
var_name : str
    Name of variable as CSDMS Standard Name.
src : array_like
    Array of new values.
indices : array_like
    Array of indices.
File:      ~/Dev/phreeqpy_project/phreeqpy/.pixi/envs/default/lib/python3.14/site-packages/phreeqcrm/phreeqcrm.py
Type:      method

In [1]:
import platform

In [3]:
platform.platform()

'macOS-26.2-arm64-arm-64bit-Mach-O'